### ISSUE TITLE
install.sh fails

### ISSUE THREAD

**Issue by sg84** [dtag-dev-sec/t-pot-autoinstall#43] opened 2018-05-22 14:51 UTC
Hi, running the autoinstall script on Ubuntu 16.04 LTS fails at installing docker-compose:

```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-10.0.1
### Installing docker-compose.
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```
I've had a quick search around the issue and it looks like it may be a change in the way pip 10 works but can't be sure.

Deleting the install.log file and creating a NGINX default file at /etc/nginx/sites-enabled/default for the script to install script to run seems to be a workaround.

Thanks,

Stu

**Comment by t3chn0m4g3** [comment] 2018-05-23 10:26
Looks like your installation is out of the standard path for `pip` which should reside on Ubuntu in `/usr/local/bin/pip` rather than `/usr/bin/pip`.
What installation media did you use? Maybe it is a modified image from a hosting provider?

**Comment by musevg** [comment] 2018-05-23 16:44
Same issue here with a plain install from original Ubuntu ISO with latest updates.
I did some tests: apt-get install python-pip installs pip 8.1.1 as /usr/bin/pip but no /usr/local/bin/pip.
apt-get install python3-pip does the same. 
Looks like install.sh adds pip 10.0.1 in /usr/local/bin and breaks 8.1.1 in /usr/bin at the same time.

**Comment by sg84** [comment] 2018-05-24 07:17
@t3chn0m4g3 It's in Azure, but it looks like a pretty standard image from Canonical.

**Comment by t3chn0m4g3** [comment] 2018-05-25 10:22
For T-Pot we are using the Netinstall image, which installs pip in `/usr/local/bin/pip`, as does the Ubuntu 18.04 desktop, server and netinstall image.

For now I propose to just symlink it: `ln -s /usr/bin/pip /usr/local/bin/pip` 

@sg84, @musevg: Please let us know if that fixes things for you.

@t3chn0m4g3
dtag-dev-sec/tpotce/issues/189

**Comment by musevg** [comment] 2018-05-25 16:15
My Ubuntu 16.04.4 server image install doesn't install any `pip`, neither in `/usr/bin` nor in `/usr/local/bin`. Maybe this is caused by me coosing just "SSH Server" in the software selection dialog during installation. 
But `apt-get install python-pip` and then linking `ln -s /usr/bin/pip /usr/local/bin/pip` does the job: `install.sh` now works as it should. Thanks.

**Comment by t3chn0m4g3** [comment] 2018-05-25 19:20
@Musevg With install I mean the location after T-Pot installs its dependencies / after running apt install. Symlink will be taken care of in next release. Thanks for feedback and reporting.

**Comment by elie195** [comment] 2018-06-03 16:43
I ran into the same issue on a fresh Ubuntu 16.04 install. The following workaround worked for me (line 306 in install.sh):

Old:
`pip install --upgrade pip`

New:
`pip install --upgrade pip && hash -r pip`

**Comment by arejaycodes** [comment] 2018-06-05 00:18
@elie195 your fix worked perfect! thanks for posting it

**Comment by t3chn0m4g3** [comment] 2018-07-31 12:01
Assuming this is resolved. Closing for now.

**Closed by t3chn0m4g3** 2018-07-31 12:01 UTC
